name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "aradhanak"
          password: "Mon$oon777"
          
      - name: Build Docker image
        run: docker build -t aradhanak/wisecow1:latest .

      - name: Push Docker image
        run: docker push aradhanak/wisecow1:latest